version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Thor@host.docker.internal:5432/sm-auto
      - DB_HOST=host.docker.internal
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sm-auto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Thor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: