version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:anything@host.docker.internal:5433/SMA
      - DB_HOST=host.docker.internal
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: SMA
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anything
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: