"""fix_notification_user_id_types

Revision ID: 56ff3da010a8
Revises: eb9a8ecf98c6
Create Date: 2025-07-30 13:04:34.963523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ff3da010a8'
down_revision: Union[str, Sequence[str], None] = 'eb9a8ecf98c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
