"""checkout

Revision ID: 782efb329a84
Revises: 25583af9c95e
Create Date: 2025-07-28 18:15:12.352960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782efb329a84'
down_revision: Union[str, Sequence[str], None] = '25583af9c95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reel_thumbnail_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('reel_thumbnail_filename', sa.String(), nullable=True))
    op.add_column('scheduled_posts', sa.Column('reel_thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_posts', 'reel_thumbnail_url')
    op.drop_column('posts', 'reel_thumbnail_filename')
    op.drop_column('posts', 'reel_thumbnail_url')
    # ### end Alembic commands ###
