"""small

Revision ID: 801b0ece4e7f
Revises: 132bf75572d7
Create Date: 2025-07-29 16:08:10.811971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '801b0ece4e7f'
down_revision: Union[str, Sequence[str], None] = '132bf75572d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_replies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_replies_pkey'))
    )
    # ### end Alembic commands ###
